rules:
  default:
    protection:
      enforce_admins: true
      restrictions:
        teams:
        - fhir-committers-mergify
      required_status_checks:
        contexts:
        - FHIR Pull Request Status
      required_pull_request_reviews: null
